server:
  port: @server.port@
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true #开启健康检查(需要spring-boot-starter-actuator依赖)
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_IP-ADDRESS:${spring.cloud.client.ipAddress}}:${server.port}



spring:
  application:
    name: turbine

turbine:
  appConfig: serviceCustomer
  aggregator:
    clusterConfig: TEST-TURBINE
  clusterNameExpression: metadata['cluster']

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework.security: ERROR

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always