debug: false

server:
  port: 9999

security:
  oauth2:
    resource:
      id: oauth2-resource
      token-info-uri: http://localhost:8080/oauth/check_token
      prefer-token-info: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG