spring:
  rabbitmq:
    addresses: 192.168.198.128:5672
    username: guest
    password: guest

zuul:
  routes:
    serviceProducer:
      serviceId: serviceProducer
      path: /serviceProducer/**
    uaa:
      serviceId: uaa
      path: /uaa/**
      ignored-patterns: /uaa/check_token
      sensitive-headers:
    serviceCustomer:
      serviceId: serviceCustomer
      path: /serviceCustomer/**
  sensitive-headers: Cookie,Set-Cookie
