spring.rabbitmq.addresses: 192.168.198.128:5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

zuul.routes.serviceProducer.serviceId: serviceProducer
zuul.routes.serviceProducer.path: /serviceProducer/**

zuul.routes.uaa.serviceId: uaa
zuul.routes.uaa.path: /uaa/**
zuul.routes.uaa.ignored-patterns: /uaa/check_token
zuul.routes.uaa.sensitive-headers:

zuul.routes.serviceCustomer.serviceId: serviceCustomer
zuul.routes.serviceCustomer.path: /serviceCustomer/**
zuul.routes.sensitive-headers: Cookie,Set-Cookie
