spring:
  rabbitmq:
    addresses: 192.168.198.128:5672
    username: guest
    password: guest

security:
  user:
    name: fadffsedfsf
    password: rrfdaDSFfesnmhf
    role: CLIENT_A,CLIENT_B
  basic:
    path: /sayHello,/hiMan

