version: "3"
services:
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/eureka:1.0
    container_name: eureka
    ports:
      - 8761:8761
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s

  config:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/config:1.0
    container_name: config
    ports:
      - 7000:7000
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - eureka
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
  auth:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth:1.0
    container_name: auth
    ports:
      - 8080:8080
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    depends_on:
      - config
      - eureka
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s

  zuul:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/zuul:1.0
    container_name: zuul
    ports:
      - 8088:8088
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    depends_on:
      - config
      - eureka
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s