version: "3"
services:
  config:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/config:1.0
    ports:
      - 7000:7000
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 2
        delay: 10s

  auth:
    image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth:1.0
    ports:
      - 8080:8080
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS={{.Node.Hostname}}
    volumes:
      - /data/logs:/data/logs
    depends_on:
      - config
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 2
        delay: 10s