server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
      hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false #关闭eureka的自我保护 踢出已关闭的节点
    eviction-interval-timer-in-ms: 600 #清理间隔时间，单位为毫秒

security:
  user:
    name: eureka
    password: 123456

endpoints:
  restart:
    enabled: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    com.weilus: DEBUG
    com.netflix.eureka: ERROR
    org.springframework: INFO




