server:
  port: 8081

spring:
  rabbitmq:
    addresses: 192.168.198.128:5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true
    threadpool:
      serviceProducer:
        coreSize: 20

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
