server:
  port: @server.port@
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  security:
    user:
      name: sba-user
      password: sba-pwd

eureka:
  client:
    healthcheck:
      enabled: true #必须放在application.yml,开启健康检查(需要spring-boot-starter-actuator依赖)
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  NFLoadBalancerRuleClassName:

feign-call:
  ribbon:
    NFLoadBalancerRuleClassName:  com.weilus.commons.ribbon.rules.DebugRibbonRule  # DEBUG 优先策略

feign:
  hystrix:
    enabled: true #开启熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
zuul:
  add-host-header: true
  sensitive-headers: #无敏感 HttpHeader, 默认Cookie,Set-Cookie,Authorization,当前微服务自己实现鉴权
  add-proxy-headers: true

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework.security: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    servlet:
      context-path: /actuator



