server:
  port: 8088
eureka:
  client:
    healthcheck:
      enabled: true #必须放在application.yml,开启健康检查(需要spring-boot-starter-actuator依赖)
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  NFLoadBalancerRuleClassName:

feign-call:
  ribbon:
    NFLoadBalancerRuleClassName:  com.weilus.commons.ribbon.rules.DebugRibbonRule  # DEBUG 优先策略

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework.security: DEBUG

zuul:
  add-host-header: true
  sensitive-headers: #无敏感 HttpHeader, 默认Cookie,Set-Cookie,Authorization,当前微服务自己实现鉴权
  add-proxy-headers: true


management:
  security:
    enabled: false


