debug: false
server:
  port: 8081
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
eureka:
  client:
    healthcheck:
      enabled: true #必须放在application.yml,开启健康检查(需要spring-boot-starter-actuator依赖)

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    addresses: 192.168.198.128:5672
    username: guest
    password: guest
security:
  basic:
    path: /sayHello,/hiMan
  user:
    name: fadffsedfsf
    password: rrfdaDSFfesnmhf

feign:
  hystrix:
    enabled: true #开启熔断
  client:
    config:
      feign-service:
        logger-level: full    #NONE,BASIC,HEADERS,FULL
        connect-timeout: 30000    #连接超时
        read-timeout:  10000      #响应超时
        request-interceptors:
          - com.weilus.commons.feign.interceptors.AuthFeignServiceInterceptor  #访问的账号密码
          - com.weilus.commons.feign.interceptors.DebugRequestInterceptor      #传递DEBUG参数到下一个服务

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE #信号量隔离模式

feign-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.weilus.commons.ribbon.rules.DebugRibbonRule # DEBUG 优先策略

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: INFO
    com.feign.clients: DEBUG
    com.weilus: DEBUG
    org.springframework.jdbc: DEBUG

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

