server:
  port: 8761
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
spring:
  application:
    name: eureka
  boot:
    admin:
      client:
        url: http://192.168.198.1:8888
#        username: admin
#        password: admin

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true #开启健康检查(需要spring-boot-starter-actuator依赖)
  server:
    enable-self-preservation: false #关闭eureka的自我保护 踢出已关闭的节点
    eviction-interval-timer-in-ms: 600 #清理间隔时间，单位为毫秒
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

security:
  user:
    name: eureka
    password: 123456

endpoints:
  restart:
    enabled: false

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    com.weilus: DEBUG
    com.netflix.eureka: ERROR
    org.springframework: INFO

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



