server:
  port: @server.port@

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: eureka
  security:
    user:
      name: eureka
      password: 123456

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true #开启健康检查(需要spring-boot-starter-actuator依赖)
  server:
    enable-self-preservation: false #关闭eureka的自我保护 踢出已关闭的节点
    eviction-interval-timer-in-ms: 600 #清理间隔时间，单位为毫秒
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_IP-ADDRESS:${spring.cloud.client.ip-address}}:${server.port}

endpoints:
  restart:
    enabled: false

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.eureka: ERROR
    org.springframework: INFO