debug: false
server:
  port: 8080

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

eureka:
  client:
    healthcheck:
      enabled: true #必须放在application.yml,开启健康检查(需要spring-boot-starter-actuator依赖)

spring:
  thymeleaf:
    cache: false

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.apache.ibatis: INFO
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always