server:
  port: @server.port@
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: admin
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
      turbine:
        location: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@192.168.198.128:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_IP-ADDRESS:${spring.cloud.client.ipAddress}}:${server.port}

turbine:
  appConfig: serviceCustomer
  aggregator:
    clusterConfig: TEST-TURBINE
  clusterNameExpression: metadata['cluster']

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework: INFO

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: admin
