server:
  port: @server.port@
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
      discovery:
        ignored-services: ${spring.application.name}
      turbine:
        location: ${spring.application.name}
        clusters: ${turbine.aggregator.clusterConfig}

turbine:
  appConfig: FEIGN-CALL
  instanceUrlSuffix: actuator/hystrix.stream              #  managemant.context-path/hystrix.stream
  aggregator:
    clusterConfig: TEST-TURBINE,FEIGN
  clusterNameExpression: metadata['cluster']

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@192.168.198.128:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_IP-ADDRESS:${spring.cloud.client.ipAddress}}:${server.port}

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework: INFO