server:
  port: @server.port@
management:
  port: @management.port@

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: admin
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /mm
      ui:
        title: 服务监控中心
      metadata-keys-to-sanitize:


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@192.168.198.128:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #租赁更新时间间隔，默认30，即10秒发送一次心跳
    lease-expiration-duration-in-seconds: 60  #租期到期时间，默认90秒
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_IP-ADDRESS:${spring.cloud.client.ipAddress}}:${server.port}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
      management.port: ${management.port}

logging:
  file: ${log.dir:@log.dir@}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework: INFO



management:
  context-path: /mm
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  basic:
    path: /mm
  user:
    name: sba-user
    password: sba-pwd
