debug: false

security:
  ignored: /oauth/check_token

spring:
  redis:
    database: 0
    host: 192.168.198.128
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/test?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: weilus
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 6000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000

mybatis:
  typeAliasesPackage: com.weilus.dto,com.weilus.entity
  mapperLocations: classpath*:mybatis/*Mapper.xml

logging:
  level:
    com.weilus: DEBUG
    org.springframework.security: DEBUG