debug: false

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
      grant-type: password
      access-token-validity-seconds: 60
      refresh-token-validity-seconds: 360
  ignored: /oauth/check_token

spring:
  redis:
    database: 0
    host: 192.168.198.128
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: DEBUG