debug: false
server:
  port: 8080
security:
  oauth2:
    resource:
      jwt:
        key-uri:

  ignored: /oauth/check_token

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: uaa
  redis:
    database: 0
    host: 192.168.100.2
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.2:3306/test?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: weilus
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 6000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000

mybatis:
  typeAliasesPackage: com.weilus.dto,com.weilus.entity
  mapperLocations: classpath*:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    com.weilus: DEBUG
    org.springframework.security: DEBUG